# Docs for the Azure Web Apps Deployment action:
# https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - health12313

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build project (if needed)
        run: npm run build --if-present

      - name: Run tests (if available)
        run: npm run test --if-present

      - name: Create deployment package
        run: |
          mkdir deploy
          shopt -s extglob
          cp -r !(deploy|release.zip|node_modules|.git|.github) deploy/
          zip -r release.zip deploy

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'health12313'
          slot-name: 'Production'
          package: deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_806F80CFD8C14AB9A8362843BB00576A }}
